/* Maré Editorial: ferramentas operacionais modulares, com feedback imediato e cópia simples. */
import { ArrowUpRight, Calculator, Clipboard, ClipboardCheck, Coins, ExternalLink, MessageSquareText, WalletCards } from "lucide-react";
import { roomOptions, type QuoteLanguage } from "@/lib/quote";
import { loftMessage } from "./dashboardData";

type Props = {
  quote: string; quoteResult: string; quoteCopied: boolean; quoteProperty: string; quoteGuests: number; quoteRoom: string; quoteLanguage: QuoteLanguage;
  total: number; percentage: number; currencyValue: number; currency: string; loft: string; copied: boolean;
  onQuoteChange: (value: string) => void; onQuoteGenerate: () => void; onQuoteCopy: () => void; onPropertyChange: (value: string) => void; onGuestsChange: (value: number) => void; onRoomChange: (value: string) => void; onLanguageChange: (value: QuoteLanguage) => void;
  onTotalChange: (value: number) => void; onPercentageChange: (value: number) => void; onCurrencyValueChange: (value: number) => void; onCurrencyChange: (value: string) => void; onLoftChange: (value: string) => void; onCopyText: (text: string) => void;
};

const formatMoney = (value: number, currency = "BRL") => new Intl.NumberFormat("pt-BR", { style: "currency", currency }).format(value);

export default function ToolsPanel(props: Props) {
  const { quote, quoteResult, quoteCopied, quoteProperty, quoteGuests, quoteRoom, quoteLanguage, total, percentage, currencyValue, currency, loft, copied } = props;
  const loftText = loftMessage.replace("{num}", loft);
  return (
    <section id="ferramentas" className="panel tools-panel tide-surface"><div className="panel-heading"><div><p className="eyebrow">ROTINAS DA RECEPÇÃO</p><h2>Ferramentas rápidas</h2><p>Pequenos fluxos que deixam o atendimento mais leve.</p></div></div><div className="tools-grid">
      <div className="tool-card"><div className="tool-title"><span className="tool-icon"><WalletCards size={18} /></span><div><h3>Gerador de cotação</h3><p>Transforme os dados da Cloudbeds em uma mensagem pronta.</p></div></div><div className="quote-filter-grid"><label>Pousada<select value={quoteProperty} onChange={event => props.onPropertyChange(event.target.value)}><option>Pousada Centro Class</option><option>Pousada Casa Centro</option><option>Pousada Centro Up</option><option>Solar João Fernandes</option></select></label><label>Pessoas<input type="number" min="1" value={quoteGuests} onChange={event => props.onGuestsChange(Number(event.target.value))} /></label><label>Tipo de quarto<select value={quoteRoom} onChange={event => props.onRoomChange(event.target.value)}>{roomOptions[quoteProperty].map(room => <option key={room}>{room}</option>)}</select></label><label>Idioma<select value={quoteLanguage} onChange={event => props.onLanguageChange(event.target.value as QuoteLanguage)}><option>Português</option><option>Español</option><option>English</option><option>Italiano</option></select></label></div><textarea value={quote} onChange={event => props.onQuoteChange(event.target.value)} placeholder="Ex.: Sex, Ago. 21 - Seg, Ago. 24\n\nTotal da Acomodação:\nR$670,00" rows={4} /><button className="primary-button" onClick={props.onQuoteGenerate}>Gerar cotação <ArrowUpRight size={16} /></button>{quoteResult && <div className="quote-result"><div className="quote-result-head"><div><span className="source-heading">RESULTADO DA COTAÇÃO</span><strong>Pronto para enviar</strong></div><button onClick={props.onQuoteCopy}>{quoteCopied ? <ClipboardCheck size={15} /> : <Clipboard size={15} />} {quoteCopied ? "Copiado" : "Copiar cotação"}</button></div><textarea value={quoteResult} readOnly rows={8} /></div>}</div>
      <div className="tool-card"><div className="tool-title"><span className="tool-icon"><MessageSquareText size={18} /></span><div><h3>Mensagem do loft</h3><p>Escolha o número e copie a mensagem de chegada.</p></div></div><div className="loft-row">{Array.from({ length: 8 }, (_, index) => String(index + 1).padStart(2, "0")).map(number => <button key={number} onClick={() => props.onLoftChange(number)} className={loft === number ? "selected" : ""}>{number}</button>)}</div><div className="copy-preview"><span>Loft {loft}</span><button onClick={() => props.onCopyText(loftText)}>{copied ? <ClipboardCheck size={16} /> : <Clipboard size={16} />} {copied ? "Copiado" : "Copiar mensagem"}</button></div></div>
      <div className="tool-card mini-tools"><div className="tool-title"><span className="tool-icon"><Calculator size={18} /></span><div><h3>Calculadora de comissão</h3><p>Veja o valor líquido rapidamente.</p></div></div><div className="inline-fields"><label>Total<input type="number" value={total} onChange={event => props.onTotalChange(Number(event.target.value))} /></label><label>%<input type="number" value={percentage} onChange={event => props.onPercentageChange(Number(event.target.value))} /></label></div><div className="percentage-result"><div className="percentage-result-title"><span>Resultados</span><small>Base de cálculo: {formatMoney(total)}</small></div><div className="percentage-line"><span>Valor Total da Reserva</span><strong>{formatMoney(total)}</strong></div><div className="percentage-line"><span>Porcentagem aplicada</span><strong>{percentage.toFixed(2).replace(".00", "")} %</strong></div><div className="percentage-line commission"><span>Valor do Desconto/Comissão</span><strong>{formatMoney(total * percentage / 100)}</strong></div><div className="percentage-line final"><span>Valor Final (com desconto)</span><strong>{formatMoney(total - (total * percentage / 100))}</strong></div></div></div>
      <div className="tool-card mini-tools currency-tool"><div className="tool-title"><span className="tool-icon"><Coins size={18} /></span><div><h3>Conversor de moedas</h3><p>Referência média para atendimento.</p></div></div><div className="inline-fields"><label>Valor em BRL<input type="number" value={currencyValue} onChange={event => props.onCurrencyValueChange(Number(event.target.value))} /></label><label>Para<select value={currency} onChange={event => props.onCurrencyChange(event.target.value)}><option value="USD">USD</option><option value="EUR">EUR</option><option value="ARS">ARS</option></select></label></div><div className="calc-result"><span>Referência do painel</span><strong>{currency === "USD" ? "$ " : currency === "EUR" ? "€ " : "ARS "}{(currencyValue * (currency === "USD" ? 0.18 : currency === "EUR" ? 0.16 : 250)).toFixed(2)}</strong></div><div className="source-list"><span className="source-heading">Consultar outras referências</span><a href="https://wise.com/gb/currency-converter/brl-to-usd-rate" target="_blank" rel="noreferrer"><span><b>Wise</b><small>taxa comercial + margem</small></span><ExternalLink size={13} /></a><a href="https://www.xe.com/currencyconverter/convert/?Amount=1&From=BRL&To=USD" target="_blank" rel="noreferrer"><span><b>XE</b><small>mid-market</small></span><ExternalLink size={13} /></a><a href="https://www.remessaonline.com.br/cotacao/cotacao-dolar" target="_blank" rel="noreferrer"><span><b>Remessa Online</b><small>cotação para remessa</small></span><ExternalLink size={13} /></a></div><small className="currency-disclaimer">O valor acima é uma estimativa de referência. As empresas podem aplicar spread, tarifas e condições próprias.</small></div>
    </div></section>
  );
}
